### ISSUE TITLE
Kmesh and Cilium

### ISSUE THREAD

**Issue by ravaga** [kmesh-net/kmesh#317]
**Please provide an in-depth description of the question you have**:
I came across this project while reading some of the KubeEdge repo documentation. I can see that Kmesh runs network functions directly in the kernel instead of using sidecar containers, which leads to clear advantages as shown in the performance comparison with Istio. However, this have been achieved by Cilium, which is under the CNCF umbrella and is a more mature project. Therefore, I would like to ask you if Kmesh presents any advantages over Cilium or what the differences are between both projects.

Thank you very much in advance.

**Comment by hzxuzhonghu** [comment]
Thank you for your question @ravaga 
Assume you are saying cilium servcie mesh here. FYI, in the [arch graph](https://cilium.io/use-cases/service-mesh/), we can see, cilium service mesh using ebpf and node local envoy. Both bpf prog and envoy are controlled by the cilium agent from the same node. 

While [kmesh] (https://github.com/kmesh-net/kmesh/blob/main/docs/pics/kmesh-arch.svg) also make use of ebpf, but for L7 traffic management, we are introducing a waypoint component, which can  stands merely for a service or a tenant.

Compared with cilium, we can say kmesh L7 proxy is more fine-grained, providing better security policy, resource isolation, and also higher availability with any number of proxies. 

In the case of component upgrading, kmesh wonot break application traffic, while cilium actually do.

As to UX, in order to make use of cilium service mesh, users has to understand almost native envoy configuration, it is boring and could be error-prone because of lacking central conrol plane and no validation in cental.  While kmesh using native istio as control plane. We provider better UX, and native user better understaning api, and also support [Gateway API](https://gateway-api.sigs.k8s.io/)

**Comment by ravaga** [comment]
Thank you very much for your response @hzxuzhonghu , now I can understand better the differences between both projects, although both use ebpf.

I'll be following your advances and test your service mesh solution in the future, which seems to be promising.

**Comment by hzxuzhonghu** [comment]
Thanks for your following, feel free to reach out to me if you have any question later
