### ISSUE TITLE
RDS Not Updating after kmesh long periods of Inactivity 

### ISSUE THREAD

**Issue by PerforMance308** [kmesh-net/kmesh#964]
**What happened**:

After running KMesh for an long period without any operations, RDS stops updating. The following observations were made:
1. KMesh is left running overnight without any operations.
2. The next day, modifications to the existing VirtualService do not take effect. For example, changing the match prefix in a VirtualService from` /test` to `/test-echo` does not update.
3. Restarting KMesh resolves the issue temporarily.
4. Debugging logs indicate that only CDS and EDS updates are happening, while RDS is not updating.

**What you expected to happen**:

Modifications to VirtualService should be applied without needing to restart KMesh.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start KMesh and configure a VirtualService with match prefix /test.
1. Allow KMesh to run overnight without any operations.
1. Modify the VirtualService to match prefix /test-echo.
1. Observe that the update does not take effect.

**Anything else we need to know?**:

**Environment**:
- Kmesh version: 0.5
- K8S Node OS: HCE 2.0 with enhanced kernel
- Others:

**Comment by hzxuzhonghu** [comment]
Can you enable kmesh debug log level and paste the log here?

**Comment by hzxuzhonghu** [comment]
What istiod version? And @lec-bit and I fixed a similar bug in v0.5 https://github.com/kmesh-net/kmesh/pull/890

**Comment by PerforMance308** [comment]
istio v1.19

**Comment by PerforMance308** [comment]
[log.txt](https://github.com/user-attachments/files/17422549/log.txt)

After line 283 of this log file, I performed an update operation on the VirtualService, only modifying the match prefix. The content printed shows that no RDS update was received.

**Comment by hzxuzhonghu** [comment]
I suspect this is due to this part of code directly.

https://github.com/kmesh-net/kmesh/blob/e5b802841dfe2e1c5c755ad9b19f0fff6f35dd23/pkg/controller/ads/ads_processor.go#L283-L287

We do not cleanup `p.Cache.routeNames` even when xds connection reconnected, so after reconnect, this route name check maybe equal(because only vs match prefix updated here.) 

Actually on istiod side, a new xds connection will not share any info with previous connection, so it has no info about what route names the client subscribed, So it will have no route at all, then no need to push

**Comment by hzxuzhonghu** [comment]
@lec-bit I donot see a fix filed, can you open a pr for it

**Comment by lec-bit** [comment]
ok
